### ISSUE TITLE
After export, no actual credits show, only the logo.

### ISSUE THREAD

**Issue by plosee** [Bytezz/godot-credits#1]
I do have a custom font, but that shouldn't matter since it works everywhere else. I thought maybe the issue is because the .ini file doesn't export properly and then the script can't find it after export, but I'm not really smart enough to make assumptions here. Inside the engine the credits work flawlessly.

**Comment by plosee** [comment]
Fixed it by adding *.ini to export settings. my bad.

**Comment by tarositos** [comment]
> Fixed it by adding *.ini to export settings. my bad. @plosee 

Hi, I'm having the same issue. It's my first time using godot, so could you please be more specific as to how you fixed it? Thank you!!

**Comment by plosee** [comment]
When you're starting to export your game, you have some additional options before clicking the export button and somewhere there you can add files that you want to export with the game iirc

bad explanation since i dont have godot installed atm

**Comment by tarositos** [comment]
> When you're starting to export your game, you have some additional options before clicking the export button and somewhere there you can add files that you want to export with the game iirc
> 
> bad explanation since i dont have godot installed atm

![image](https://github.com/Bytezz/godot-credits/assets/152926546/c7ffa729-d420-4d22-8b2d-727d3a34a388)

is it here? because i tried all these extensions and i still cant get it to work.

**Comment by Bytezz** [comment]
For me, using `credits-scene/example-CREDITS.ini` as credits file, adding `*.ini` to "Filters to export non-resource files/folders" is enough (Godot 4.x).

<details> 
<summary>Screenshots</summary>

![image](https://github.com/Bytezz/godot-credits/assets/25850701/3d5ccc85-0766-4c44-bf85-ea851f0d092d)
![image](https://github.com/Bytezz/godot-credits/assets/25850701/443e369d-7c20-4628-be7e-19216dfd1fcd)
![image](https://github.com/Bytezz/godot-credits/assets/25850701/dd403119-a901-4060-b910-bbe3aa40f436)

 </details>

Otherwise you can directly add the entire path to file.
<details> 
<summary>Screenshot</summary>

![image](https://github.com/Bytezz/godot-credits/assets/25850701/228349a5-200b-4741-a89d-ee99d95d44a2)

 </details>
